# Generated by Django 4.0.3 on 2022-04-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AddQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('login_id', models.CharField(max_length=70)),
                ('pasword', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Fmale')], default='m', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('birthday', models.DateField(blank=True, max_length=70, null=True)),
                ('adres_1', models.TextField(blank=True, max_length=370, null=True)),
                ('adres_2', models.TextField(blank=True, max_length=370, null=True)),
                ('city', models.TextField(blank=True, max_length=370, null=True)),
                ('state', models.TextField(blank=True, max_length=370, null=True)),
                ('country', models.TextField(blank=True, max_length=370, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('show_entries', models.IntegerField(default=10)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('select_level', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], default='m', max_length=1)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('login_id', models.CharField(max_length=70)),
                ('pasword', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('birthday', models.DateField(blank=True, max_length=70, null=True)),
                ('adres_1', models.TextField(blank=True, max_length=370, null=True)),
                ('adres_2', models.TextField(blank=True, max_length=370, null=True)),
                ('city', models.TextField(blank=True, max_length=370, null=True)),
                ('state', models.TextField(blank=True, max_length=370, null=True)),
                ('country', models.TextField(blank=True, max_length=370, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('show_entries', models.IntegerField(default=10)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='', max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_question', models.TextField(max_length=700)),
                ('option1', models.TextField(max_length=300)),
                ('option2', models.TextField(max_length=300)),
                ('option3', models.TextField(max_length=300)),
                ('option4', models.TextField(max_length=300)),
                ('answer', models.TextField(max_length=300)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.addquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=30)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('topic_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topicdetail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='addquestion',
            name='select_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topic'),
        ),
    ]
